<?php

namespace Database\Seeders;

use DateTime;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class QuestionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table("questions")->insert([
            [
                "section_id" => 1,
                "content" => "問い1",
                "theme" => "we",
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "section_id" => 1,
                "content" => "問い2",
                "theme" => "went",
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "section_id" => 1,
                "content" => "問い3",
                "theme" => "visited",
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "section_id" => 1,
                "content" => "問い4",
                "theme" => "visited to",
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "section_id" => 1,
                "content" => "問い5",
                "theme" => "the",
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "section_id" => 1,
                "content" => "問い6",
                "theme" => "museum",
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "section_id" => 1,
                "content" => "問い7",
                "theme" => "go",
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "section_id" => 1,
                "content" => "問い8",
                "theme" => "I",
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "section_id" => 1,
                "content" => "問い9",
                "theme" => "I",
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "section_id" => 1,
                "content" => "問い10",
                "theme" => "looked",
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "section_id" => 1,
                "content" => "問い11",
                "theme" => "at",
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "section_id" => 1,
                "content" => "問い12",
                "theme" => "John",
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "section_id" => 1,
                "content" => "問い13",
                "theme" => "listened",
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "section_id" => 1,
                "content" => "問い14",
                "theme" => "theme",
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "section_id" => 1,
                "content" => "問い15",
                "theme" => "park",
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "section_id" => 1,
                "content" => "問い16",
                "theme" => "bank",
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "section_id" => 1,
                "content" => "問い17",
                "theme" => "gym",
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "section_id" => 1,
                "content" => "問い18",
                "theme" => "station",
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "section_id" => 1,
                "content" => "問い19",
                "theme" => "zoo",
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "section_id" => 1,
                "content" => "問い20",
                "theme" => "discussed",
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "section_id" => 1,
                "content" => "問い21",
                "theme" => "matter",
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "section_id" => 1,
                "content" => "問い22",
                "theme" => "problem",
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "section_id" => 1,
                "content" => "問い23",
                "theme" => "schedule",
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "section_id" => 1,
                "content" => "問い24",
                "theme" => "plan",
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "section_id" => 1,
                "content" => "問い25",
                "theme" => "talked",
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "section_id" => 2,
                "content" => "meeting",
                "theme" => "meeting",
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "section_id" => 2,
                "content" => "get up",
                "theme" => "get up",
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "section_id" => 2,
                "content" => "eat out",
                "theme" => "eat out",
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "section_id" => 2,
                "content" => "at a party",
                "theme" => "at a party",
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "section_id" => 3,
                "content" => "up",
                "theme" => "up",
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "section_id" => 3,
                "content" => "stop",
                "theme" => "stop",
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "section_id" => 3,
                "content" => "it",
                "theme" => "it",
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "section_id" => 3,
                "content" => "get",
                "theme" => "get",
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "section_id" => 3,
                "content" => "good",
                "theme" => "good",
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "section_id" => 3,
                "content" => "bad",
                "theme" => "bad",
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "section_id" => 3,
                "content" => "make",
                "theme" => "make",
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "section_id" => 3,
                "content" => "look",
                "theme" => "look",
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "section_id" => 3,
                "content" => "big",
                "theme" => "big",
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "section_id" => 4,
                "content" => "stop it",
                "theme" => "stop it",
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "section_id" => 4,
                "content" => "good idea",
                "theme" => "good idea",
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "section_id" => 4,
                "content" => "make up",
                "theme" => "make up",
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "section_id" => 4,
                "content" => "look up",
                "theme" => "look up",
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "section_id" => 4,
                "content" => "make up again",
                "theme" => "make up again",
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "section_id" => 4,
                "content" => "look at",
                "theme" => "look at",
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
        ]);
    }
}
