<?php

namespace Database\Seeders;

use DateTime;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VideoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table("videos")->insert([
            [
                "url" => "Ij1o5zGDCeE",
                "question_id" => 1,
                "start_time" => 215.8,
                "answer" => "We don't just live as individuals, we live embedded in a society",
                "end_time" => 220,
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "url" => "2Oe6HUgrRlQ",
                "question_id" => 2,
                "start_time" => 323,
                "answer" => "John Wesley, who went up and down this country delivering sermons,",
                "end_time" => 326.8,
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "url" => "o1Z4F4e2Bw4",
                "question_id" => 3,
                "start_time" => 375,
                "answer" => "a place that had been barely visited by paleontologists.",
                "end_time" => 379,
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "url" => "22aeMgJ5cWY",
                "question_id" => 4,
                "start_time" => 313,
                "answer" => 'As late as 1952 when Arthur Miller visited to research "The Crucible", the subject of witchcraft was taboo.',
                "end_time" => 320.8,
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "url" => "Ij1o5zGDCeE",
                "question_id" => 5,
                "start_time" => 70,
                "answer" => 'and often commits great harm in the present in order to get there.',
                "end_time" => 74.4,
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "url" => "2Oe6HUgrRlQ",
                "question_id" => 6,
                "start_time" => 657.3,
                "answer" => "That's why a very common feeling when you're in a museum",
                "end_time" => 660.3,
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "url" => "Ij1o5zGDCeE",
                "question_id" => 7,
                "start_time" => 89.9,
                "answer" => "the idea that we are going to go back to some imaginary past",
                "end_time" => 93.25,
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "url" => "C-GrRIgdmW8",
                "question_id" => 8,
                "start_time" => 4,
                "answer" => "I played this chord that was so wrong I thought",
                "end_time" => 13,
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "url" => "DjcZrtcBZi4",
                "question_id" => 9,
                "start_time" => 804.2,
                "answer" => "I don't know if you've ever looked at the credits of a Pixar movie,",
                "end_time" => 807,
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "url" => "JW8dqT90BLs",
                "question_id" => 10,
                "start_time" => 33,
                "answer" => "us to peer at the primary building blocks of matter--",
                "end_time" => 36,
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "url" => "F8Rwz3KWFHA",
                "question_id" => 10,
                "start_time" => 242,
                "answer" => "First, we have talked about Britain's decision to leave",
                "end_time" => 245,
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "url" => "2Oe6HUgrRlQ",
                "question_id" => 11,
                "start_time" => 248.26,
                "answer" => "in there, we'll find a lot of the truths that we might previously have found in the Gospel of Saint John.",
                "end_time" => 253.26,
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "url" => "8i-pNVj5KMw",
                "question_id" => 12,
                "start_time" => 543,
                "answer" => "pastors, journalists, European pen-pals. They listened to him, prayed with him, helped him question himself.",
                "end_time" => 554,
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "url" => "uzKBGtf0i0M",
                "question_id" => 13,
                "start_time" => 18,
                "answer" => "When I first heard this theme,",
                "end_time" => 20,
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "url" => "8dKFDr4pFWw",
                "question_id" => 14,
                "start_time" => 764,
                "answer" => "building You had to take everyone out of",
                "end_time" => 766,
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "url" => "8dKFDr4pFWw",
                "question_id" => 15,
                "start_time" => 249,
                "answer" => "That is very different from a traditional bank card where 75%",
                "end_time" => 254.5,
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "url" => "7n9IOH0NvyY",
                "question_id" => 16,
                "start_time" => 784,
                "answer" => "less likely to be put on medication, more likely to go to the gym,",
                "end_time" => 788,
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "url" => "aOPPpsgdPdI",
                "question_id" => 17,
                "start_time" => 53,
                "answer" => "The gas station has definitely become",
                "end_time" => 57,
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "url" => "V5jjIHaKd-8",
                "question_id" => 18,
                "start_time" => 84,
                "answer" => "For me, the zoo was a way to get to know my camera",
                "end_time" => 88,
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "url" => "F8Rwz3KWFHA",
                "question_id" => 19,
                "start_time" => 301,
                "answer" => "We've also discussed the threat from Islamist terrorism.",
                "end_time" => 304,
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "url" => "aOPPpsgdPdI",
                "question_id" => 20,
                "start_time" => 203,
                "answer" => "In the grand scheme of things, no matter what celebrity is wearing your jeans or",
                "end_time" => 209,
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "url" => "JW8dqT90BLs",
                "question_id" => 21,
                "start_time" => 33,
                "answer" => "us to peer at the primary building blocks of matter for whatever reason",
                "end_time" => 37,
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "url" => "oKtALHe3Y9Q",
                "question_id" => 22,
                "start_time" => 168,
                "answer" => "the first step to solving any problem is to not hide from it,",
                "end_time" => 172,
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "url" => "3OgsRa7VDtI",
                "question_id" => 23,
                "start_time" => 243,
                "answer" => "are over budget or behind schedule.",
                "end_time" => 245.5,
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "url" => "DjcZrtcBZi4",
                "question_id" => 24,
                "start_time" => 413,
                "answer" => "learning where you act, as opposed to plan, your way to the future.",
                "end_time" => 417,
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "url" => "etQJ1FUbOxk",
                "question_id" => 25,
                "start_time" => 147,
                "answer" =>  "one of the reason I love doing this work is because I talk to so many amazing people",
                "end_time" => 151.5,
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "url" => "8dKFDr4pFWw",
                "question_id" => 26,
                "start_time" => 165.7,
                "answer" =>  "It started off as a card and I don't call it luxury, I call it meeting the needs of the customer.",
                "end_time" => 172,
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "url" => "JtUZOsghoV4",
                "question_id" => 27,
                "start_time" => 96,
                "answer" =>  "that's not enough of a story help you get up in the morning,",
                "end_time" => 100.1,
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "url" => "yxuu__Etbtk",
                "question_id" => 28,
                "start_time" => 70.5,
                "answer" =>  "You might say let's eat out Saturday night.",
                "end_time" => 72.5,
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "url" => "FMvNoJvQqNw",
                "question_id" => 29,
                "start_time" => 21,
                "answer" =>  "Is it good for stand-up, or is it good for saying at a party",
                "end_time" => 27,
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "url" => "DjcZrtcBZi4",
                "question_id" => 30,
                "start_time" => 33,
                "answer" =>  "I spent nearly a decade observing up close and personal",
                "end_time" => 37,
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "url" => "7bB_fVDlvhc",
                "question_id" => 31,
                "start_time" => 897.6,
                "answer" =>  "First thing: stop seeing a book like a one-time event.",
                "end_time" => 901.2,
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "url" => "7bB_fVDlvhc",
                "question_id" => 31,
                "start_time" => 897.6,
                "answer" =>  "First thing: stop seeing a book like a one-time event.",
                "end_time" => 901.2,
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "url" => "C-GrRIgdmW8",
                "question_id" => 32,
                "start_time" => 36,
                "answer" =>  "It took me years to figure out what actually happened.",
                "end_time" => 40,
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "url" => "Ij1o5zGDCeE",
                "question_id" => 33,
                "start_time" => 70,
                "answer" =>  "and often commits great harm in the present in order to get there.",
                "end_time" => 74,
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "url" => "9axG7EhGNmI",
                "question_id" => 34,
                "start_time" => 395,
                "answer" =>  "I mean, I think a lot of that's just through really good curation.",
                "end_time" => 398,
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "url" => "2Oe6HUgrRlQ",
                "question_id" => 35,
                "start_time" => 629.7,
                "answer" =>  "The two really bad ideas that are hovering in the modern world",
                "end_time" => 632.9,
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "url" => "C-GrRIgdmW8",
                "question_id" => 36,
                "start_time" => 59,
                "answer" =>  "try to do, and that is try to make anything that happens",
                "end_time" => 64,
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "url" => "DjcZrtcBZi4",
                "question_id" => 37,
                "start_time" => 56.9,
                "answer" =>  "that we analyzed and looked for patterns in what our leaders did.",
                "end_time" => 59.9,
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "url" => "ddxHlkIuHqg",
                "question_id" => 38,
                "start_time" => 41,
                "answer" =>  "I loved growing up in a big family.",
                "end_time" => 45,
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "url" => "emHAoQGoQic",
                "question_id" => 39,
                "start_time" => 152.3,
                "answer" =>  "And you really have to stop it if you want to be sane.",
                "end_time" => 156,
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "url" => "BOJvlWi0_yQ",
                "question_id" => 40,
                "start_time" => 31.3,
                "answer" =>  "Then that ends up being a good idea.",
                "end_time" => 33.9,
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "url" => "SEAIQ62rydI",
                "question_id" => 41,
                "start_time" => 945.2,
                "answer" =>  "Somebody has to make up the difference.",
                "end_time" => 946.6,
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "url" => "7oUCSfeM9PY",
                "question_id" => 42,
                "start_time" => 377,
                "answer" =>  "The first thing I'm going to do is look up who I'm buying from.",
                "end_time" => 381,
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "url" => "UWhj-5PAwgg",
                "question_id" => 43,
                "start_time" => 0,
                "answer" =>  "Hey guys, it's Libbey and today I thought that I would make a video doing my make-up again",
                "end_time" => 7,
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
            [
                "url" => "DjcZrtcBZi4",
                "question_id" => 44,
                "start_time" => 313,
                "answer" =>  "So when we look at why it is that Pixar is able to do what it does,",
                "end_time" => 319,
                "created_at" => new DateTime(),
                "updated_at" => new DateTime(),
            ],
        ]);
    }
}
